apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rulebooks-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gm-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gm-bot
  template:
    metadata:
      labels:
        app: gm-bot
    spec:
      containers:
      - name: gm-bot
        image: localhost:32000/gm-bot:latest
        ports:
        - containerPort: 8080
        env:
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: gm-bot-secrets
              key: SLACK_SIGNING_SECRET
        - name: LLM_BASE_URL
          valueFrom:
            secretKeyRef:
              name: gm-bot-secrets
              key: LLM_BASE_URL
        - name: LLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: gm-bot-secrets
              key: LLM_API_KEY
        - name: LLM_MODEL
          valueFrom:
            secretKeyRef:
              name: gm-bot-secrets
              key: LLM_MODEL
        - name: DISCORD_PUBLIC_KEY
          value: e412eb27351ffed20cf0dcf71f7bd4de9c201f7c5947bb2a6e4c88480e28714e
        - name: RULEBOOKS_PATH
          value: /rulebooks
        volumeMounts:
        - name: rulebooks
          mountPath: /rulebooks
          readOnly: true
      volumes:
      - name: rulebooks
        persistentVolumeClaim:
          claimName: rulebooks-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gm-bot-service
spec:
  selector:
    app: gm-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gm-bot-ingress
spec:
  # https://github.com/STRRL/cloudflare-tunnel-ingress-controller
  ingressClassName: cloudflare-tunnel
  rules:
  - host: gm-bot.cyberdeck.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gm-bot-service
            port:
              number: 80
